### ISSUE TITLE
Adjoints todo

### ISSUE THREAD

**Issue by teseoch** [polyfem/polyfem#235]
- [x] add tutorial to docs
- [ ] merge adjoint solver https://github.com/polyfem/polyfem/pull/234#discussion_r1298637234
- [ ] create assemblers for adjoints parts in forms https://github.com/polyfem/polyfem/pull/234#discussion_r1298658915 https://github.com/polyfem/polyfem/pull/234#discussion_r1298657199
- [ ] adjoints and convergent ipc https://github.com/polyfem/polyfem/pull/234#discussion_r1298661195
- [ ] face and cell jacobian https://github.com/polyfem/polyfem/pull/234/files#r1298652493 https://github.com/polyfem/polyfem/pull/234#discussion_r1298653311
- [ ] merge sparse and dense newton https://github.com/polyfem/polyfem/pull/234#discussion_r1298654381

**Comment by teseoch** [comment]
Closing this old adjoint TODO since the remaining adjoint work is tracked in a newer issue.
